stages:
  - test
  - image

test-job:
  stage: test
  image: alpine:3.20.3
  dependencies: []
  script:
    - apk add py3-aiohttp py3-aiosqlite py3-yarl
    - python3 -m unittest

image-job:
  stage: image
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  rules:
    - if: $CI_COMMIT_TAG
