services:
  llm-billing-proxy:
    image: registry.comtegra.pl/comtegra/llm-billing-proxy:latest  # set a specific version here
    command: "-c /run/secrets/llm-billing-proxy-config.toml"
    secrets: [llm-billing-proxy-config.toml]
    ports: [8080:8080]  # set HOST_PORT:CONTAINER_PORT here
    #networks: [backend, l3out]  # networks if needed

secrets:
  llm-billing-proxy-config.toml:
    file: ./secrets/llm-billing-proxy-config.toml  # set the location of your config file here
