log_level = "INFO"
host = "0.0.0.0"
port = 8080
timeout_connect = 5  # backend connection timeout
timeout_read = 60  # backend response timeout
#cert = "example.crt"
#key = "example.key"

[db]
uri = "mongodb://llm-billing-proxy:mypass@mongohost:27017/?authSource=cgc"

[backends.llama31-70b]
url = "https://llm-server.comtegra.cgc-waw-01.comtegra.cloud"
token = "MY-TOKEN1"

[backends.llama3-sqlcoder-8b]
url = "https://llm-server2.comtegra.cgc-waw-01.comtegra.cloud"
token = "MY-TOKEN2"

[backends.llama31-8b]
url = "https://llm-server-bis.comtegra.cgc-waw-01.comtegra.cloud"
token = "MY-TOKEN3"
